version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

      - image: circleci/postgres:alpine-postgis-ram
        name: db
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            sudo apt-get update && sudo apt-get install -y \
                    gdal-bin python-gdal python3-gdal
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py makemigrations app
            python3 manage.py migrate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: app
